services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=monster_db
      - POSTGRES_USER=monsterini
      - POSTGRES_PASSWORD=monsterini_secretini
    ports:
      - '5151:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
