###
POST http://localhost:8080/api/questionnaire
Content-Type: application/json

{
  "placeTypes": ["Cafés & Coffee Shops", "Parks & Green Spaces"],
  "ageRange": "20-25",
  "occupation": "Student",
  "usualPlaces": "Bliri liriri.",
  "user": { "id": 1 }
}

###

POST /api/sidequest/generate HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "userId": 1,
  "preference": "I want a restaurant ",
  "count": 1
}
